# Generated by Django 3.2.6 on 2021-10-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Tipo de Servidor', max_length=50)),
                ('Version', models.CharField(help_text='Version', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Nombre del Servidor', max_length=50)),
                ('IP', models.CharField(help_text='IP del servidor', max_length=20)),
                ('ServerType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.servertypes')),
            ],
        ),
    ]
