# Generated by Django 3.2.6 on 2021-10-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(help_text='Nombre del la Rutina', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationName', models.CharField(help_text='Nombre de la Ubicación', max_length=50)),
                ('FilesPath', models.CharField(help_text='Ubicación fisica', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(help_text='Estatus', max_length=20)),
                ('Description', models.CharField(help_text='Descripcion del Status', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DatabaseName', models.CharField(help_text='Nombre de la BD', max_length=20)),
                ('FriendlyName', models.CharField(help_text='Alias de la BD', max_length=50)),
                ('Server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.servers')),
            ],
        ),
    ]
