# Generated by Django 3.2.6 on 2021-10-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_databases_job_locations_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
