# Generated by Django 3.2.6 on 2021-10-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_rename_job_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationDate', models.DateField(blank=True, help_text='Fecha de Creación', null=True)),
                ('StartBackup', models.DateTimeField(blank=True, help_text='Inicio de generación del backup', null=True)),
                ('EndBackup', models.DateTimeField(blank=True, help_text='Terminación del Backup', null=True)),
                ('FileName', models.CharField(help_text='Nombre del archivo', max_length=100)),
                ('SizeMB', models.DecimalField(decimal_places=2, help_text='Tamaño en MB', max_digits=20)),
                ('Size', models.BigIntegerField(help_text='Tamaño')),
                ('Comments', models.TextField(help_text='Comentarios')),
                ('Database', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.databases')),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.jobs')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.locations')),
                ('Status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.status')),
            ],
        ),
    ]
