# Generated by Django 3.2.6 on 2021-11-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_alter_backups_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.SmallIntegerField(help_text='No.Regla')),
                ('Rule', models.CharField(help_text='Nombre de la regla', max_length=40)),
                ('Status', models.SmallIntegerField(choices=[(1, 'Activa'), (2, 'Inactiva')], default=1, max_length=2)),
                ('RetentionDays', models.SmallIntegerField(help_text='Dias de retención')),
                ('FIleFormat', models.CharField(help_text='Formato del backup', max_length=6)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.jobs')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_location', to='backups.locations')),
            ],
        ),
    ]
