# Generated by Django 3.2.6 on 2021-11-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='Status',
            field=models.SmallIntegerField(choices=[(1, 'Activa'), (2, 'Inactiva')], default=1),
        ),
    ]
