# Generated by Django 3.2.6 on 2021-11-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0007_alter_rotation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotation',
            old_name='FIleFormat',
            new_name='FileFormat',
        ),
    ]
